### ISSUE TITLE
Wrong Latitude

### ISSUE THREAD

**Issue by kumarabnit** [hkellaway/HNKGooglePlacesAutocomplete#105]
Hi, 
I am using this hnk_placemarkFromGooglePlace method for getting Latitude and Longitude from CLPlacemark.  i am using this to select two location on the map and mapping the distance. Using this i am getting wrong Latitude for one of the location. I tried searching location on Google map on the web and getting wrong address on map.

**Comment by haidalinda** [comment]
is it that the hnk_placemarkFromGooglePlace function is extracting the wrong value (i.e. it’s logic is wrong); or that Google provides the incorrect value in its Google Placd model?

**Comment by kumarabnit** [comment]
Function hnk_placemarkFromGooglePlace is providing wrong value according to the location display in the list.

**Comment by haidalinda** [comment]
is the Google Maps API (not what you see on the website, rather what is returned to the Objective-C library) the correct value? 

The question being is it the Google Places API (not the Google website) or the library that has the incorrect value

**Comment by kumarabnit** [comment]
Google Maps API is returning correct value when using current location and in any other scenario. When Using the hnk_placemarkFromGooglePlace for selected location from the list , the location name i am getting is correct but CLPlacemark data is wrong. I mean when i fetch latitude and longitude for the selected location from the list is has different value from the selected list.

**Comment by haidalinda** [comment]
im not really sure what the issue is in this specific case - and it sounds like it’s one scenario. i would recommend implementing custom logic for your app to transform from CLPlacemark to the Google Place model.
