### ISSUE TITLE
How to use specific key for iOS only with the library ?

### ISSUE THREAD

**Issue by rahulvyas** [hkellaway/HNKGooglePlacesAutocomplete#107]
SInce google has changed places api's. I've created a new key specific to iOS Apps and added bundle identifier of my app on google console. Enabled places,maps etc services. But I'm getting error when using the key. If I use no restrictions it works.

ERROR: Error Domain=com.hnkgoogleplacesautocomplete.query.fetch.error Code=4 "This IP, site or mobile application is not authorized to use this API key. Request received from IP address 49.206.191.33, with empty referer" UserInfo={NSLocalizedDescription=This IP, site or mobile application is not authorized to use this API key. Request received from IP address 49.206.191.33, with empty referer, NSLocalizedFailureReason=This IP, site or mobile application is not authorized to use this API key. Request received from IP address 49.206.191.33, with empty referer}

**Comment by haidalinda** [comment]
i no longer actively maintain this library or keep up with the integration needs on the Google end - apologies! If you find a solution to your issue, please post back

**Comment by rahulvyas** [comment]
Thanks for the response :)
