### ISSUE TITLE
Unable to use when API key is restricted

### ISSUE THREAD

**Issue by rahulvyas** [hkellaway/HNKGooglePlacesAutocomplete#108]
When we restrict the key we always get error This IP, site or Mobile application is not authorized to use this API key. Request received from IP address (Some IP Address), with empty referer.

**Comment by haidalinda** [comment]
hi @rahulvyas i’m not sure what that message means - also unclear if it’s specific to the library or to Google services. i don’t actively maintain this library and it’s been deprecated for a couple years. of course, feel free to fork and fix if you’l find it’s a library issue

**Comment by rahulvyas** [comment]
@hkellaway The issue is we get error if we add restriction otherwise it works fine. Any advice where I should look into code ?

**Comment by haidalinda** [comment]
@rahulvyas that sounds like an aspect of Google services then, not the library

Perhaps looking closer at the error in this callback would give more detail:
https://github.com/hkellaway/HNKGooglePlacesAutocomplete/blob/3338d18de981f0d90671a24e544d04f70fbef1aa/Pod/Classes/HNKGooglePlacesAutocompleteQuery.m#L247

**Comment by rahulvyas** [comment]
Thanks, will look into it.
