### ISSUE TITLE
Could not fetch Places

### ISSUE THREAD

**Issue by HieuLsw** [hkellaway/HNKGooglePlacesAutocomplete#70]
- I have created gooogle api key for ios and enable google places api service-> run project i get error : 
  Could not fetch Places. Request denied. They key parameter may be invalid. Does goole places api for ios is current not run

**Comment by haidalinda** [comment]
That message means a `REQUEST_DENIED` error code was returned by the API - this can happen for different reasons, the most common being your API key is invalid or you've exceeded your quota.

Try the following request in you web browser, replacing `API_KEY` with your API_KEY:

https://maps.googleapis.com/maps/api/place/autocomplete/json?input=Vict&types=geocode&language=fr&key=API_KEY

You should be seeing:

``` json
{
   "predictions" : [
      {
         "description" : "Victoria, Australie",
         "id" : "0328fb981d48f228012b5d4b7ab0d0f404f439fd",
         "matched_substrings" : [
            {
               "length" : 4,
               "offset" : 0
            }
         ],
         "place_id" : "ChIJT5UYfksx1GoRNJWCvuL8Tlo",
         "reference" : "CjQrAAAAg_gXd98JZtd9ZxrreklT5VAHXpoqgsHctNY0xP1uXPJoVfkljfONhABGACGxDzBgEhD46nIc0qYOKKq-3btyH6FkGhQFtzaf0e94kmXVkni3CMLiZlntEw",
         "terms" : [
            {
               "offset" : 0,
               "value" : "Victoria"
            },
            {
               "offset" : 10,
               "value" : "Australie"
            }
         ],
         "types" : [ "administrative_area_level_1", "political", "geocode" ]
      },
      {
         "description" : "Victoria, BC, Canada",
         "id" : "d5892cffd777f0252b94ab2651fea7123d2aa34a",
         "matched_substrings" : [
            {
               "length" : 4,
               "offset" : 0
            }
         ],
         "place_id" : "ChIJcWGw3Ytzj1QR7Ui7HnTz6Dg",
         "reference" : "CjQsAAAAh8iIsHxGgWXBF4KgwXkAtkgz8YgrdJGELppdlgJ-ooJVxogxdDGZW1LmiQyAxytPEhBHTCfPbn7QBNXvGj5AutInGhRJ862c41o3kQAaAq2s8tI40Rro4g",
         "terms" : [
            {
               "offset" : 0,
               "value" : "Victoria"
            },
            {
               "offset" : 10,
               "value" : "BC"
            },
            {
               "offset" : 14,
               "value" : "Canada"
            }
         ],
         "types" : [ "locality", "political", "geocode" ]
      },
...
```

If you're not, your API key is likely invalid. If you are, there may be an issue with the way the pod is being used in your app.

**Comment by haidalinda** [comment]
@HieuLsw did you have any luck with my comment above? ^

**Comment by HieuLsw** [comment]
can you show me how to create api key? i think i my api key is incorrect:(

**Comment by haidalinda** [comment]
- Head to Google Developers Console https://console.developers.google.com/project
- Hit 'Create Project' to make a project specific to your app
- Once that's created, look at the left-hand menu and hit 'APIs & Auth' > APIs 
- Search for 'Places' and Enable 'Google Places Web Service'
- Once enabled, look at the left-hand menu and hit 'Credentials'
- Hit 'Create new Key' > 'Server key' > Create
- Key should be listed next to 'API key'

**Comment by haidalinda** [comment]
If that doesn't work, i'm not sure what more I can do :/

**Comment by haidalinda** [comment]
@HieuLsw hope that worked. i'll be closing this if i don't hear back for another day as this kind of support is a bit outside the scope of the project

**Comment by HieuLsw** [comment]
oh, great jobs. tks you

**Comment by chlebta** [comment]
Hello, I've created API key for IOS app but I get this issue : 

```
2015-08-27 09:39:30.228 HNKGooglePlacesAutocomplete-Example[2120:619868] ERROR: Error Domain=com.hnkgoogleplacesautocomplete.query.fetch.error Code=4 "Request denied. The key parameter may be invalid." UserInfo=0x1ad76b10 {NSLocalizedFailureReason=Request denied. The key parameter may be invalid., NSLocalizedDescription=Request denied. The key parameter may be invalid.}
```

**Comment by haidalinda** [comment]
It is likely the API key is invalid - please see the discussion above, one way to check is to see if you can successfully fetch data in your browser. One gotcha with creating the API key is that you should be working with Google's Places Web Service. 

I hope those comments help. Further troubleshooting is really  out of the scope of support for this project, as having an invalid API key does not represent an issue with the pod itself.

**Comment by mitchellporter** [comment]
For anyone else that comes across this issue, there are 2 gotcha's that can cause these errors:
1. Even though it's an iOS app, you're using the web API, so request a Server key.
2. If you then receive a warning that the API key has expired, you simply need to wait 10 minutes for the new API key to be activated.

**Comment by polkandra** [comment]
Everything works with apple maps,but when I use google maps,table view with autocompletion is hidden under google maps itself. When I change map's frame, table view becomes visible.Harlan can u help,what's wrong here???
