### ISSUE TITLE
Calculate distance form current location

### ISSUE THREAD

**Issue by NirmitDagly** [hkellaway/HNKGooglePlacesAutocomplete#81]
Hello,
Thanks for making such a nice library. I want to ask a question that Can I calculate distance from my current location to the places that I've searched by using this library? Also, how can I get the selected search place's latitude and longitude?

Thanks,
Nirmit D.

**Comment by haidalinda** [comment]
this library does not provide that functionality. perhaps to do so, you could use the library to turn the Places into CLPlacemarks, which have a `location` property; the `location` property on CLPlacemark's has a `coordinate` property which has a `latitude` and `longitude`
