### ISSUE TITLE
Is it possible to cancel an ongoing request?

### ISSUE THREAD

**Issue by Ricardo1980** [hkellaway/HNKGooglePlacesAutocomplete#85]
Is it possible to cancel an ongoing request?

I have this problem:
http://stackoverflow.com/questions/33692599/how-can-i-cancel-an-ongoing-request-in-gmsplacesclient-autocompletequery

Thanks.

**Comment by haidalinda** [comment]
@Ricardo1980 there's no specific way build into this library to cancel an ongoing request
