### ISSUE TITLE
Location bias

### ISSUE THREAD

**Issue by mitchellporter** [hkellaway/HNKGooglePlacesAutocomplete#87]
First off, just wanted to say thanks for putting this library together. Love the fact that it isn't tied to a special controller subclass.

I have a quick question about the location bias settings. The entire reason why I'm using this library is because it wraps the web API instead of the Google Maps / Places iOS SDK which lacks location bias features I need.

Anyways, I was prepared to start looking into how to tweak the location bias settings for this library, but now that I have it setup at a basic level, I realized that it's already doing what I need. As I search for places, it's showing me the results in order of closest to farthest and they're all relevant to my current location.

I haven't provided any location or coordinates data to `HNKGooglePlacesAutocomplete` or to any Google Maps / Places SDK classes. How is this working?

I can see that there are some default config settings in `HNKGooglePlacesAutocompleteQueryConfig` but I don't see how those would be giving me the results I'm getting.

Definitely not complaining, as I'm getting the results I need with location bias without any customization, just curious how it's actually working so I can continue to tweak/customize if I need to do more.

Thanks.

**Comment by haidalinda** [comment]
this is actually an interesting aspect of the API itself:

```
If you do not supply the location and radius, the API will attempt to detect the user's location from their IP address, and will bias the results to that location. If you would prefer to have no location bias, set the location to '0,0' and radius to '20000000' (20 thousand kilometers), to encompass the entire world.
```

if you want to change that bias, that's when the `HNKGooglePlacesAutocompleteQueryConfig` object comes into play. by default, the config has those default values - which the library translates into not wanting a bias

**Comment by mitchellporter** [comment]
@hkellaway Awesome thanks for the info 👍🏻
