### ISSUE TITLE
CLPlacemark missing important data

### ISSUE THREAD

**Issue by mitchellporter** [hkellaway/HNKGooglePlacesAutocomplete#88]
Once I have a `HNKGooglePlacesAutocompletePlace` object, I'm calling `hnk_placemarkFromGooglePlace` to get the `CLPlacemark` object.

I was logging the `CLPlacemark` and could see the data I wanted in the console, but couldn't figure out how to access it. After doing some investigating, it looks like the majority of this data must be part of a private class object or something, any chance I can get some input on this? I realize it's probably something I can't get access to, but I'd still like to know what's actually happening to cause this.

Either way, I need more of the data that is provided in Google's raw JSON response if I can't get access to the data via the `CLPlacemark`. Is there any alternative you can think of? Any modification I could make to the current codebase fairly easily to get the rest of the data that seems to be hidden away for some reason?

As a last resort I could fork and make sure the raw JSON is passed all the way to the final completion block so I can access what I need and go from there.

Thanks for the input and advice.

**Comment by mitchellporter** [comment]
I did some more digging and found out there is a way to access this information: http://stackoverflow.com/a/33409788/3344977

This looks a little to hacky for my tastes and looks like it could have the potential to break at any given time. What do you think?

**Comment by haidalinda** [comment]
one thought is to wrap the CLPlacemark call with your own - as illustrated here: https://github.com/hkellaway/HNKGooglePlacesAutocomplete/issues/86

the individual in that issue mentions the data they need is in the Google Place Details call and they may take a hand at adding a Google Place Details model to the library so that can be returned in the callback. If you do end up doing something like that, I'd encourage you to submit a PR.

hope that helps in some manner.

**Comment by mitchellporter** [comment]
@hkellaway I'm locked into this project right now and on a deadline so I ended up just passing the raw JSON back in the completion block but I'm going to add this to my list of github to-do's and will submit a proper PR doing exactly what you described in the near future.

**Comment by haidalinda** [comment]
:+1:
