### ISSUE TITLE
Support for Afnetworking 3.0

### ISSUE THREAD

**Issue by leosalmaso** [hkellaway/HNKGooglePlacesAutocomplete#91]
After updated to afnetworking 3.0 the autocomplete stop working, actually the project stop build. Is there any solution for that issue?

**Comment by haidalinda** [comment]
the pod relies on AFNetworking 2.5. i'm not sure the difference between AFNetworking 2.x and 3.x - or the implications of trying to use a different version of the same pod that another pod depends on - well enough to tell you why it stopped working all together.

i can update the pod to rely on AFNetworking 3.0, but i'll be honest that it's not my top priority right now, so i have no guarantee when that might happen

**Comment by leosalmaso** [comment]
Actually the only thing that is needed is allow the pod compatibility with Afnetworking 2.5+. You don't need to change nothing in the source code. But currently if the project has added Afnetworking 3.0, the library throw an error because it is looking for version 2.5.

**Comment by haidalinda** [comment]
ah, i see what you're saying. i'll make a release in the coming days with AFNetworking 3.0

**Comment by haidalinda** [comment]
@leitosalma updated as of version 1.2.0 :tada:
