### ISSUE TITLE
Swift 3.0

### ISSUE THREAD

**Issue by muzamilhassan1987** [hkellaway/HNKGooglePlacesAutocomplete#98]
How to use it in Swift or is this available in swifT?

**Comment by haidalinda** [comment]
this library is in Objective-C and there are no plans to convert it to Swift. i haven't attempted to use it with a Swift project, so i'm not sure how integrating would go. if it doesn't work out-of-the-box - perhaps try Swift libraries, like https://github.com/watsonbox/ios_google_places_autocomplete or https://github.com/geek1706/swift-google-autocomplete
